"""add SentinelX SOC entity models

Revision ID: 18f66b3d1cfa
Revises: 2552464e6222
Create Date: 2026-09-11 19:01:57.182132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f66b3d1cfa'
down_revision: Union[str, Sequence[str], None] = '2552464e6222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_agent_id'), 'hosts', ['agent_id'], unique=True)
    op.create_index(op.f('ix_hosts_hostname'), 'hosts', ['hostname'], unique=True)
    op.create_index(op.f('ix_hosts_id'), 'hosts', ['id'], unique=False)
    op.create_index(op.f('ix_hosts_ip_address'), 'hosts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_hosts_is_active'), 'hosts', ['is_active'], unique=False)
    op.create_index(op.f('ix_hosts_last_seen'), 'hosts', ['last_seen'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_id'), 'threat_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_indicator'), 'threat_intelligence', ['indicator'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_indicator_type'), 'threat_intelligence', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_source'), 'threat_intelligence', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['telemetry_events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_event_id'), 'incident_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_events_relationship_type'), 'incident_events', ['relationship_type'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_action_type'), 'response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_actions_id'), 'response_actions', ['id'], unique=False)
    op.create_index(op.f('ix_response_actions_incident_id'), 'response_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_response_actions_requested_by'), 'response_actions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_response_actions_status'), 'response_actions', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['detection_findings.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_finding_id'), 'alerts', ['finding_id'], unique=False)
    op.create_index(op.f('ix_alerts_host_id'), 'alerts', ['host_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_host_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_finding_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_response_actions_status'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_requested_by'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_incident_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_type'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_incident_events_relationship_type'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_event_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_intelligence_source'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_indicator_type'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_indicator'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_hosts_last_seen'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_is_active'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_ip_address'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_hostname'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_agent_id'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
